tailwind.config = {
    darkMode: "class",
    theme: {
        extend: {
            "colors": {
                "impact-blue-dark": "#003D7A",
                "on-tertiary-container": "#d9cdca",
                "error-container": "#ffdad6",
                "surface-dim": "#dadada",
                "primary-fixed-dim": "#acc7ff",
                "on-secondary-container": "#6c5000",
                "inverse-primary": "#acc7ff",
                "tertiary-container": "#5f5754",
                "on-primary-container": "#bbd0ff",
                "warm-gold": "#E6AC00",
                "tertiary-fixed": "#ece0dc",
                "on-primary-fixed": "#001a40",
                "surface-container": "#eeeeee",
                "tertiary-fixed-dim": "#cfc4c1",
                "surface-container-high": "#e8e8e8",
                "on-primary-fixed-variant": "#004491",
                "pure-white": "#FFFFFF",
                "secondary-fixed-dim": "#fabd00",
                "on-surface-variant": "#424752",
                "primary-container": "#0056b3",
                "on-surface": "#1a1c1c",
                "surface-container-highest": "#e2e2e2",
                "inverse-on-surface": "#f1f1f1",
                "secondary-fixed": "#ffdf9e",
                "primary-fixed": "#d7e2ff",
                "surface-variant": "#e2e2e2",
                "deep-onyx": "#1A1A1A",
                "secondary-container": "#fdc003",
                "surface-container-lowest": "#ffffff",
                "surface": "#f9f9f9",
                "tertiary": "#47403d",
                "on-secondary": "#ffffff",
                "surface-tint": "#115cb9",
                "primary": "#003f87",
                "error": "#ba1a1a",
                "on-secondary-fixed-variant": "#5b4300",
                "on-tertiary-fixed-variant": "#4d4543",
                "surface-container-low": "#f3f3f3",
                "outline": "#727784",
                "on-error": "#ffffff",
                "on-error-container": "#93000a",
                "on-background": "#1a1c1c",
                "background": "#f9f9f9",
                "secondary": "#785900",
                "outline-variant": "#c2c6d4",
                "on-tertiary-fixed": "#201a18",
                "surface-bright": "#f9f9f9",
                "on-primary": "#ffffff",
                "on-tertiary": "#ffffff",
                "on-secondary-fixed": "#261a00",
                "inverse-surface": "#2f3131"
            },
            "borderRadius": {
                "DEFAULT": "0.25rem",
                "lg": "0.5rem",
                "xl": "0.75rem",
                "full": "9999px"
            },
            "spacing": {
                "xl": "80px",
                "gutter": "24px",
                "sm": "12px",
                "md": "24px",
                "base": "8px",
                "xs": "4px",
                "container-max": "1280px",
                "lg": "48px"
            },
            "fontFamily": {
                "body-lg": ["DM Sans"],
                "display-xl": ["DM Sans"],
                "headline-lg-mobile": ["DM Sans"],
                "headline-lg": ["DM Sans"],
                "label-sm": ["Hanken Grotesk"],
                "headline-md": ["DM Sans"],
                "body-md": ["DM Sans"]
            },
            "fontSize": {
                "body-lg": ["18px", {"lineHeight": "28px", "fontWeight": "400"}],
                "display-xl": ["64px", {"lineHeight": "72px", "letterSpacing": "-0.02em", "fontWeight": "700"}],
                "headline-lg-mobile": ["32px", {"lineHeight": "40px", "fontWeight": "700"}],
                "headline-lg": ["40px", {"lineHeight": "48px", "letterSpacing": "-0.01em", "fontWeight": "700"}],
                "label-sm": ["14px", {"lineHeight": "20px", "letterSpacing": "0.05em", "fontWeight": "600"}],
                "headline-md": ["24px", {"lineHeight": "32px", "fontWeight": "600"}],
                "body-md": ["16px", {"lineHeight": "24px", "fontWeight": "400"}]
            }
        },
    },
}
